### ISSUE TITLE
v0.9 support (especially tags)

### ISSUE THREAD

**Issue by manuel-huez** [corley/influxdb-php-sdk#12]
The release candidate is out. Tags are very powerful, and it would be great to get them working with this SDK!

**Comment by wdalmut** [comment]
yes, you are right! We absolutely have to work on that!

**Comment by andig** [comment]
+1

**Comment by gianarb** [comment]
Hi @manuel-huez thanks for this idea, I'm reading the InfluxDB's docs and maybe this library already support this feature because to write tags InfluxDB require a new array key **tags** into the single point 
```JSON
{
    "database": "mydb",
    "retentionPolicy": "mypolicy",
    "points": [
        {
            "name": "cpu_load_short",
            "tags": {
                "host": "server01",
                "region": "us-west"
            },
            "timestamp": "2009-11-10T23:00:00Z",
            "fields": {
                "value": 0.64
            }
        }
    ]
}
```
With this library the point's structure is a simple array, you can add this key 
```PHP
$influxdbClient->mark("your.series", [
    "name" => "cpu_load_short",
    "tags" => [
        "host": "server01",
        "region": "us-west"
    ]
]);
```
In this moment I can not try this solution, if you have time can you share your tests?
Thanks!!

**Comment by manuel-huez** [comment]
The new API is actually totally different from the old one. For instance, before the database name was directly specified in the endpoint URL, and not in the request content. That's why this library doesn't support the 0.9 yet :)

**Comment by gianarb** [comment]
ooohh!!!! Thanks for this note! we can start to work about this stuff

**Comment by toddboom** [comment]
This is awesome, guys! Let us know if we can provide any v0.9.0 details to help make this easier for you.

**Comment by gianarb** [comment]
Thanks @toddboom we are starting the work.. #13 :)

**Comment by manuel-huez** [comment]
Hey, any news on this? :)

**Comment by wdalmut** [comment]
@manuel-huez we are still discussing on #13

**Comment by wdalmut** [comment]
Hi to everyone, 

at the end we select the strategy in order to support v0.9 and v0.8 of influxdb at the same time in our PHP SDK until InfluxDB releases a 1.0 version.

We select to proceed with **a single BC Break** on adapters **namespace** [check the pull request #17] and to keep untouched all public signatures.

We have moved actual HTTP and UDP/IP adapters under a new namespace: from `InfluxDB\Adapter\UdpAdapter` to `InfluxDB\Adapter\V08\UdpAdapter`

In that way we can prepare a new group of adapters in a separate namespace `InfluxDB\Adapter\V09` that will supports new InfluxDB features and endpoints and keep stable also all users that will continue with the v0.8 for a while.

## Mark new points

The mark signature is:

```php
public function mark($name, array $values, $timePrecision = false);
```

That will remains unchanged for boths v0.8 and v0.9 InfluxDB versions, but is the user responsibility to prepare the right data packet for the target InfluxDB.

### InfluxDB v0.8

Remains unchanged:

```php
$client->mark("search.result", [
  "query" => "this is my search query",
  "user" => "my-username",
]);
```

### InfluxDB v0.9

The data packet is bit different in order to support v0.9 extra features like: tagging, retention policies, etc.

```php
$client->mark("search.result", [
  "retentionPolicy" => "default",
  "tags" => [
    "region" => "eu-west-1",
    "host" => "t2.medium",
  ],
  "fields" => [
    [
      "value" => 79.123,
      "user" => "my username",
    ],
    // More points...
  ],
]);
```

Of course you can prepare a more simplier packet like:

```php
$client->mark("search.result", [
  "fields" => [
    [
      "value" => 79.123,
      "user" => "my username",
    ],
  ],
]);
```

Where default information like database name and the series name will me merged automatically by the SDK.

In order to support completely the new API behaviour, for InfluxDB v0.9, we will add a new signature's strategy allowing the user to compose a direct message (checkout the [influxdb write data section](http://influxdb.com/docs/v0.9/concepts/reading_and_writing_data.html#writing-data-using-the-http-api)).

```php
$client->mark([
    "database" => "mydb",
    "retentionPolicy" => "default",
    "points": [
        [
            "name" => "cpu_load_short",
            "tags" => [
                "host" => "server01",
                "region" => "us-west"
            ],
            "timestamp" => "2009-11-10T23:00:00Z",
            "fields": [
                "value" => 0.64
            ]
        ]
    ]
]);
```

In order to support this new strategy we will patch the `mark` method as:

```php
public function mark($name, array $values = [], $timePrecision = false);
```

in order to evaluate the first param as an `array` structure and change the SDK behaviour on the fly. 

What do you think about our plan?

**Comment by davejenniex** [comment]
Why would you do that when you can just use the Composer versions? Currently, the InfluxDB package is at 3.*, then continue to use the 3.* version if you are using InfluxDB v0.8. If you need the InfluxDB v0.9, then why not bump up the version to 4.*.

That provides less confusion for any developer wanting to use this library, and makes upgrading very easy, since there is not a lot of code to change between versions 3.* and 4.*.

**Comment by wdalmut** [comment]
@davejenniex after reading your reply i feel stupid... In my strange vision someone could use v0.8 and v0.9 at the same time in the same project... something strange effectively.

At the end we will decide to let all unchanged and just bring the new structure removing the v0.8 from sdk milestone 0.4. 

We will open a separate branch for v0.3 in order to patch possible problems with the old sdk.

Thanks for your advice...
;)

Walter

**Comment by wdalmut** [comment]
Related pull request

#29

**Comment by wdalmut** [comment]
Now we are ready to merge the PR #29 `feature/influxdb-0.9` that works with InfluxDB v0.9 release candidate 33 for HTTP and UDP/IP
